jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ../

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build --if-present
      
    - name: Run lint
      run: npm run lint
      
    - name: Run tests
      run: npm test
